Encountered an exception while running action 'action_meetup'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
local variable 'resp' referenced before assignment
Traceback (most recent call last):
  File "/Users/moaaz/.pyenv/versions/rasa365/lib/python3.6/site-packages/rasa_core/processor.py", line 302, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/Users/moaaz/development/dialogue/experiments/rasa-prototype/actions.py", line 74, in run
    resp = json.loads(resp)
UnboundLocalError: local variable 'resp' referenced before assignment
Encountered an exception while running action 'action_meetup'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
name 'ConversationResumed' is not defined
Traceback (most recent call last):
  File "/Users/moaaz/.pyenv/versions/rasa365/lib/python3.6/site-packages/rasa_core/processor.py", line 302, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/Users/moaaz/development/dialogue/experiments/rasa-prototype/actions.py", line 78, in run
    tracker.update(ConversationResumed())
NameError: name 'ConversationResumed' is not defined
